### ISSUE TITLE
Broken Python deps

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.roughnator#4]
So some of our open call friends tried to install the dev env following the steps in the README. But the `poetry install` step didn't work for them:

> When trying hacking “Roughnator”, the command “poetry install” fails in the step of installing scipy
> (specifically in pyproject.toml), so there are 7 dependencies that cannot be installed.

Find out what's broken :-)

**Comment by c0c0n3** [comment]
I couldn't manage to reproduce exactly their error, but it could be related to missing native libs. In fact, I've managed to clone the repo and install all deps on an Ubuntu VM. But then, when trying to import `scipy` I got a nasty error:

```
libz.so.1: cannot open shared object file: No such file or directory
```

# Steps to reproduce

### 1. Spin up an Ubuntu VM
```console
$ multipass launch --name roughnator --cpus 2 --mem 4G --disk 20G 20.04
$ multipass shell roughnator
```

### 2. Install Nix to get a dev shell w/ Python & Poetry
```console
$ sh <(wget -qO- https://nixos.org/nix/install)
Installation finished!  To ensure that the necessary environment variables are set, either log in again, or type
$ . /home/ubuntu/.nix-profile/etc/profile.d/nix.sh
$ mkdir -p ~/.config/nix
$ echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
$ nix shell github:c0c0n3/kitt4sme.fipy?dir=nix
$ python --version
Python 3.9.6
$ poetry --version
Poetry version 1.1.10
```

### 3. Install Python deps and get into a Poetry virtual env
```console
$ git clone https://github.com/c0c0n3/kitt4sme.roughnator.git
$ cd kitt4sme.roughnator
$ poetry install
Creating virtualenv roughnator-1MmCoZId-py3.9 in /home/ubuntu/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 38 installs, 0 updates, 0 removals

  • Installing idna (3.3)
  • Installing sniffio (1.2.0)
  • Installing anyio (3.5.0)
  • Installing certifi (2021.10.8)
  • Installing charset-normalizer (2.0.11)
  • Installing numpy (1.22.1)
  • Installing pyparsing (3.0.7)
  • Installing typing-extensions (4.0.1)
  • Installing urllib3 (1.26.8)
  • Installing asgiref (3.5.0)
  • Installing attrs (21.4.0)
  • Installing bitmath (1.3.3.1)
  • Installing click (8.0.3)
  • Installing h11 (0.13.0)
  • Installing httptools (0.3.0)
  • Installing iniconfig (1.1.1)
  • Installing joblib (1.1.0)
  • Installing packaging (21.3)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing pydantic (1.9.0)
  • Installing python-dotenv (0.19.2)
  • Installing pyyaml (6.0)
  • Installing requests (2.27.1)
  • Installing scipy (1.6.1)
  • Installing starlette (0.17.1)
  • Installing threadpoolctl (3.1.0)
  • Installing toml (0.10.2)
  • Installing uri (2.0.1)
  • Installing uvloop (0.16.0)
  • Installing watchgod (0.7)
  • Installing websockets (10.1)
  • Installing coverage (6.3)
  • Installing fastapi (0.73.0)
  • Installing pytest (6.2.5)
  • Installing scikit-learn (1.0.2)
  • Installing fipy (0.1.0 b30f670)
  • Installing uvicorn (0.17.1)

Installing the current project: roughnator (0.1.0)

$ poetry shell
Spawning shell within /home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9
```

### 4. Start Python interpreter and import scipy
```console
$ python
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libz.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/lib/python3.9/site-packages/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/ubuntu/.cache/pypoetry/virtualenvs/roughnator-1MmCoZId-py3.9/bin/python"
  * The NumPy version is: "1.22.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libz.so.1: cannot open shared object file: No such file or directory
```
